# Generated by Django 4.2.11 on 2025-08-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField()),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'distribution_centers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('zip_code', models.CharField(max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocation.distributioncenter')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
