# Generated by Django 4.2.11 on 2025-08-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributioncenter',
            name='initial_stock',
            field=models.IntegerField(default=100),
        ),
    ]
