name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: order_allocation.settings
      API_KEY: ty/>Q438I8Ds
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Create directories for mocks
        run: |
          mkdir -p logs alerts
      - name: List project structure
        run: |
          ls -R
      - name: Apply migrations
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-branch --cov-report=xml --verbose
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false